### ISSUE TITLE
Ошибка при редактировании кодов на уровне

### ISSUE THREAD

**Issue by Avablack** [drdaemos/encounter-engine#35]
Создать игру
Добавить уровень
Добавить код
Нажать редактировать https://puu.sh/Amu3g/96598a2050.png
Ведет на страницу https://autoquest.herokuapp.com/games/3/levels/5/questions/6/edit 
при переходе https://puu.sh/Amu4w/f4f4b809a4.png

**Comment by drdaemos** [comment]
чекнуть добавление тоже, у дениса на мобиле проблемы были
